# Generated by Django 3.2.5 on 2023-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterid', models.IntegerField(max_length=200)),
                ('assettype', models.CharField(choices=[('L', 'LAPTOP'), ('T', 'TRAVEL_BAG'), ('P', 'PACKAGE')], max_length=200)),
                ('numberassets', models.PositiveIntegerField(max_length=200)),
                ('dateandtime', models.DateField()),
                ('fromplace', models.CharField(max_length=200)),
                ('toplace', models.CharField(max_length=200)),
                ('todeliverperson', models.CharField(max_length=200)),
                ('deliverby', models.IntegerField(blank=True, max_length=200, null=True)),
                ('packagesensitivity', models.CharField(choices=[('H', 'HIGHLY_SENSITIVE'), ('S', 'SENSITIVE'), ('N', 'NORMAL')], max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderid', models.CharField(max_length=200)),
                ('fromplace', models.CharField(max_length=200)),
                ('toplace', models.CharField(max_length=200)),
                ('dateandtime', models.DateField()),
                ('travelmedium', models.CharField(choices=[('B', 'BUS'), ('C', 'CAR'), ('T', 'TRAIN')], max_length=200)),
                ('quantity', models.PositiveIntegerField(max_length=200)),
            ],
        ),
    ]
