# Generated by Django 3.2.5 on 2023-01-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemap', '0002_auto_20230111_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='travelmedium',
            field=models.CharField(choices=[('BUS', 'BUS'), ('CAR', 'CAR'), ('TRAIN', 'TRAIN')], max_length=200),
        ),
    ]
